name: irma-spy
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - arrow-cpp=0.11.1
  - attrs=21.4.0
  - beautifulsoup4=4.11.1
  - black=19.10b0
  - blas=1.0
  - boost-cpp=1.68.0
  - bottleneck=1.3.4
  - brotli-python=1.0.9
  - bs4=4.11.1
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - colorlover=0.3.0
  - dash-bio=0.2.0
  - dash-bootstrap-components=1.1.0
  - dash-daq=0.5.0
  - dataclasses=0.8
  - fastparquet=0.4.1
  - flask=1.1.2
  - flask-caching=1.10.1
  - html5lib=1.1
  - icu=58.2
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - ld_impl_linux-64=2.34
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.2.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libprotobuf=3.6.1
  - libstdcxx-ng=9.2.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvmlite=0.34.0
  - lxml=4.6.3
  - markupsafe=1.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mypy_extensions=0.4.3
  - ncurses=6.1
  - numba=0.51.2
  - numexpr=2.8.1
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.0.5
  - parquet-cpp=1.5.1
  - pathspec=0.7.0
  - pip=20.1.1
  - pyarrow=0.11.1
  - pyparsing=3.0.4
  - python=3.7.6
  - python-snappy=0.6.0
  - python_abi=3.7
  - readline=8.0
  - regex=2022.3.15
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=49.1.0
  - snappy=1.1.9
  - soupsieve=2.3.1
  - sqlite=3.32.3
  - tenacity=8.0.1
  - threadpoolctl=2.2.0
  - thrift=0.11.0
  - thrift-cpp=0.12.0
  - tk=8.6.10
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing_extensions=4.2.0
  - webencodings=0.5.1
  - wheel=0.34.2
  - xlrd=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.8.0
  - zlib=1.2.11
  - pip:
    - biopython==1.77
    - brotli==1.0.7
    - click==7.1.2
    - dash==1.13.3
    - dash-core-components==1.10.1
    - dash-html-components==1.0.3
    - dash-renderer==1.5.0
    - dash-table==4.8.1
    - flask-compress==1.5.0
    - future==0.18.2
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - numpy==1.19.0
    - plotly==4.8.2
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==6.0
    - retrying==1.3.3
    - six==1.15.0
    - werkzeug==1.0.1